### ISSUE TITLE
Show endpoints by method

### ISSUE THREAD

**Issue by Gildo-Sargi-Neto** [mrin9/RapiDoc#119]
First, this project is awesome, absolutely beautifull, but i wonder if the option of show the endpoints by method exists, if not, you could implement it simpler than in the swagger, like a simple array attribute of methods

![image](https://user-images.githubusercontent.com/49002665/72923613-32e6d500-3d2e-11ea-9c75-bbce6aed097d.png)
![image](https://user-images.githubusercontent.com/49002665/72923641-41cd8780-3d2e-11ea-8173-2ce0f18f33d7.png)

**Comment by mrin9** [comment]
I am not sure if you meant to `sort` the endpoints,  or `group` them by method ?
one of our earlier version had a grouping by endpoints instead of tags.  and all the methods for that endpoint will be listed together
https://mavequest.varianteffect.org/docs/api 

Try RapiDoc version `5.3.0` to checkout if thats something that you are looking for. 
unfortunately, we had to remove that feature due to poor usability-feedback we received.

if you want to sort the endpoints within each method, I can look into that option.
Let me know

**Comment by Gildo-Sargi-Neto** [comment]
i want to sort the tags by the methods kind of " in tag A i will first see all the GET  and then the POSTS, PUT etc.. " 

sorry for the bad english :(

**Comment by mrin9** [comment]
thanks for confirming, I will add this to our task list

**Comment by mrin9** [comment]
addressed it in release 7.1.1
