### ISSUE TITLE
New Feature: option to use highlightjs

### ISSUE THREAD

**Issue by croudet** [mrin9/RapiDoc#128]
I would like to use `highlightjs` because I have some code blocks in markdown description.
It looks like it is possible to set an highlighter for `marked`:
```javascript
marked.setOptions({
  highlight: function(code) {
    return require('highlight.js').highlightAuto(code).value;
  }
```

thanks

**Comment by mrin9** [comment]
Good suggestion!, I will think about it. 
We want to keep the RapiDoc bundle size low, more so because we bundle everything into a single file.

So It needs to be done in some sort of pluggable way, like allow user of rapidoc to set-options for `marked`. That way it becomes user's responsibility to provide `highlightjs` and the various language-syntax it will support.

If you have any ideas or suggestions feel free to discuss

**Comment by croudet** [comment]
I agree, it is up to the user to include `highlightjs`. We just need a way to configure rapidoc to use it.

**Comment by mrin9** [comment]
for demo checkout https://mrin9.github.io/RapiDoc/examples/code-highlight.html
