### ISSUE TITLE
Add Syntax Highlighting to Request Response

### ISSUE THREAD

**Issue by BinaryWizard904** [mrin9/RapiDoc#183]
As demonstrated on the [Code Highlight](https://mrin9.github.io/RapiDoc/examples/code-highlight.html) example, RapiDoc is capable of code highlighting.

However, for some reason this syntax highlighting is not applied to any Request Response, Response Header, or CURL code.
![RapiDoc Syntax Highlighting Issue](https://user-images.githubusercontent.com/62070150/79008047-29e1f480-7b22-11ea-8ed7-4ce93cdc3c40.png)

**Comment by mrin9** [comment]
yep, we didn't applied syntax highlighting to request and responses sections coz some of our performance tests performed badly for larger specs.
I still dont know if its our implementation or something else, but if we can achieve some acceptable performance will apply it.

**Comment by mrin9** [comment]
It is now fixed with other changes in this commit 650ee21

The second screen showing example is actually not a code-highlight. If a valid JSON example is provided RapiDoc tries to show it through a tree component that helps in expand collapse. If you provide other kind of examples such as `xml`, `text`, `html`  etc then it will just render as is, there wont be any highlighting
