### ISSUE TITLE
Improved Search

### ISSUE THREAD

**Issue by garretteklof** [mrin9/RapiDoc#205]
Hello, first off I want to say thanks for contributing to this project. I stumbled upon it after sharing a similar sentiment with Redoc's lack of support for a true 'Try' the API feature. I found you commenting on one of those issues, so I imagine this was the catalyst that brought you to making this.

This library is a true gem - I think it's very straightforward and easy to use. I know one of the main draws for me to Redoc was not only it's good-looking interface but the fact that you could import it directly as a React component. This is a completely separate thought, but FWIW I think you could see a wider adoption rate (especially these days) by sprinkling in explicit documentation on how to do this (maybe even offer a little React wrapper ala Redoc). It's obviously very simple to integrate this as a web component, but it might not hurt to spell it out for people. I know that I personally had never integrated a third-party web component into any of my React projects until stumbling across this.

OK - to the original thought - what do you think about expanding the search capabilities? My thoughts are not only searching "on type", or bringing the "plucked" links to the top (like Redoc), but perhaps integrating a little more "smarts" as well - maybe using something like [lunr.js](https://github.com/olivernn/lunr.js) or down the road offering something like Algolia support. This feature, while not absolutely imperative to my needs, is one of those compare / contrasts that's hard to pass up.

**Comment by mrin9** [comment]
Redoc's lack of Try feature is surely one of the reason but isnt the only one, 

There are plenty of other reasons ranging from usability, look-n-feel, feature-set that did not align well with our vision of API documentation. 

couple of primary reasons to create RapiDoc is 
- ReDoc and Swagger UI both are React component so the developer experience to integrate these with other libraries is not so great
- A big chunk RapiDoc's user base deals with micro services, so they have smaller but many API specs. For documentation purpose they like to show it as one integrated document.

for example check this https://www.northbricks.io/apis/ it has about 4 or 5 open-api specs tucked into one integrated view (view-page-source on the site to see how its done)

that aside 

RapiDoc has a fairly large internal user-base and many of our roadmap features are driven by them. We did various ux-survey in the past. w.r.t search what we found was most people relied on browser search than RapiDoc's own search.
- Its easy to invoke and use `cmd/ctrl-F`
- Better performs because its native
- Natively supports jumping for one search item to another

We did experimented with full site searches, it is fine with small to medium sized specs, but some of the larger specs it wasnt as snappy as we would like it to be. The browser's native search was performing better. (also on our end we like to keep RapiDoc package size small). 

you might ask why would RapiDoc even have a search then? well, thats coz, it behaves more like a filter by hiding other stuff and gives a focused view, rather than highlighting.
Many developers likes to make the documentation look smaller by pre-filtering it as per their area of interest and then navigate around it or use browser search to find stuff

But if you can provide me with some interesting reason why would you like to have a full text search within rapidoc and not use browser's native search, I will take it further

**Comment by garretteklof** [comment]
Thank you for the detailed explanation! I can clearly see now the benefits of filtering. It wasn't as intuitive with how my spec was laid out (I was searching for unique targets), not to mention I was in 'read' - and I think the functionality really shines in 'view' mode.

As semantical as it may seem, it might make sense to consider replacing the placeholder on the input with something like "filter" - however, I understand how the word "search" is much more universal. I agree that `cmd/ctrl-f` is much better suited for exact text matching- the only drawback I see to not having a full text search in the search box would be for user engagement. I see now it's intended function, but my initial gut reaction was that "the search was broken / not that good". This is could have unintended consequences for user's misjudging the validity of the UI (and in turn, the documented API itself). This is very much an off-the-cuff opinion, of course - it's just my personal conditioning that when I see a 'search box' I tend to expect ingenious, on-the-fly reporting of specific, typo-be-damned results (thanks Google).

I will close because you definitely addressed the thought process behind all of this. Thanks again!
