### ISSUE TITLE
Errors after rendering: TypeError: e.enum.map is not a function

### ISSUE THREAD

**Issue by skekec1** [mrin9/RapiDoc#207]
Hi,

we are facing a issue after the page is loaded:

<img width="580" alt="Bildschirmfoto 2020-05-07 um 12 43 56" src="https://user-images.githubusercontent.com/41141260/81285944-920ff180-9060-11ea-93e5-e9d1747f157e.png">

This error occures nearly 500 times and i think it has a bad impact on the load times.

Is this already known or en environment specific issue?

I have tried embedding rapidoc via unpack and created a local copy and load it too.

**Comment by mrin9** [comment]
I wont be able to comment much on this error unless I am able to recreate it on my end

what I can say is 
- It isnt a know issue
- most likely it is stemming from an improperly formatted spec (just a guess coz, it appears after the spec is loaded and `enum.map` in RapiDoc is only used while reading schemas from the spec)

I would suggest first try to isolate the issue 
- try with a valid and minimal spec (if the error is gone then its the spec)
- If it is still an issue then try to isolate your environment/build process   

if nothing works,

provide me with a spec so that I can generate the error on my end.

**Comment by skekec1** [comment]
Hi,

thank you for the fast response. I will try the advised steps and would open a new issue then if i know more about the issue.

Thank you!

Selcuk
