### ISSUE TITLE
Add image margin

### ISSUE THREAD

**Issue by winonecheng** [mrin9/RapiDoc#209]
As title, there is margin or padding in most of tags (`p`, `h1`, `h2`) , but not in `img`.
It result in no spacing between text and image.

**Comment by mrin9** [comment]
will you be able to provide a screenshot ?

**Comment by winonecheng** [comment]
For example:

```markdown
# Introduction

texttext

![eee](https://dataduppedings.no/subcube/Colour_Gradients/Yellow-Green_256x256.png)

....

texttext

....

![eee](https://visualidentity.columbia.edu/sites/default/files/styles/cu_crop/public/content/Colors/pms290c.jpg?)

![aaa](https://bfmbrainfall.files.wordpress.com/2015/10/red5.jpg?w=200&h=200&crop=1)

The  API is the primary way to get data out of  our platform.

```

In RapiDoc, it will show

![image](https://user-images.githubusercontent.com/11289632/81389211-0a071600-914c-11ea-99e9-eef7f059871c.png)

and in VSCode preview

![image](https://user-images.githubusercontent.com/11289632/81389288-2905a800-914c-11ea-9e5b-0c744c8ce11a.png)
![image](https://user-images.githubusercontent.com/11289632/81389301-2efb8900-914c-11ea-8f08-ba2355da7ee0.png)

**Comment by mrin9** [comment]
thanks, out of curiosity, which VS code plugin are you using to show RapiDoc preview ? we do have internal VSCode and Confluence plugins for RapiDoc, but I would rather like to contribute to some existing plugin as coz our internal plugins arent open-source

**Comment by winonecheng** [comment]
Its built-in feature in VSCode.
[Here](https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview)'s a set of example extensions that customize the preview.

**Comment by mrin9** [comment]
I see, 
you are previewing just the markdown, 
I thought you are previewing the OpenAPI Spec itself using a plugin specifically built for OpenAPI

**Comment by mrin9** [comment]
Well we ran `provide image margin` suggestion with our internal user base. Majority voted to keep things unchanged as it gives possibilities to join images and also separate them if needed. The control remains with the user rather than forcing it on them

This is also in compliant with various markdown engines and renderer

I have updated our markdown example to show various layout possibilities with images to clear things up

as shown below
![image](https://user-images.githubusercontent.com/5056899/82948775-4cf02880-9f57-11ea-93ff-56619bab1be6.png)

If you need a line gap between the image and the text then you may do that in the markdown
