### ISSUE TITLE
Content-Type not sent in request headers

### ISSUE THREAD

**Issue by darkonejr** [mrin9/RapiDoc#22]
I have a OpenAPI 2.0 doc that has both "application/json" and "application/xml"  in the produces section at the api spec level.  The generated requests don't include any Content-Type header, (which is actually required in my API to get the appropriate output).  I don't necessairly need RapiDoc to be flexible in the output types the way SwaggerUI is, but could it send Content-Type="application/json" at a minimum?

**Comment by mrin9** [comment]
When I test with https://petstore.swagger.io/v2/swagger.json it (RapiDoc) sends appropriate content-type either `application/json` or `application/xml` depending upon what the user has selected while making the request

> I have a OpenAPI 2.0 doc that has both "application/json" and "application/xml" in the produces section at the api spec level.

If you want RapiDoc to send Content-Type=`application/json` then you should fix your spec, instead of produces section set the content-type in consumes section

>I don't necessairly need RapiDoc to be flexible in the output types the way SwaggerUI is

RapiDoc dont decide the output type, it is generated by the application server and rapidoc will display  
whatever is provided by the server, If the content-type of the output happens to be application/json, RapiDoc will display the output in indented collapsible way for other types it will display as is. If plain-text then plain as plai text if `application/octet-stream` then it will download a file and so on

I feel this is the spec issue not a RapiDoc issue, If this isnt the case please feel free to reopen it and share your spec.

**Comment by darkonejr** [comment]
I can reproduce the issue with the rapidoc demo page pointing at petstore, so I'm not sure what's happening here exactly.

Here are my repro steps:

1. Open https://mrin9.github.io/RapiDoc/example2.html
2. Set API Spec to https://petstore.swagger.io/v2/swagger.json
3. Try out GET /store/inventory
4.  Response is in application/json, but that's because the API sends data out in that format by default.  Content-Type is not actually set in the request.

**Comment by darkonejr** [comment]
My mistake, I'm confusing Content-Type with Accept.  Accept headers aren't being sent in the request, not Content-Type...

**Comment by mrin9** [comment]
@darkonejr  this should be now fixed in release 4.3.0. Let me know if it works for your use-case.

**Comment by darkonejr** [comment]
Looks good!  Thank you, and sorry for the confusion.
