### ISSUE TITLE
User specified API server

### ISSUE THREAD

**Issue by jonvictory** [mrin9/RapiDoc#256]
Hello,

**Is a way for the user to specify their own API server to send their requests to?**

I've attempted to create my own custom field for this, which is designed to update the **server-url attribute** of rapidoc upon submit. In the same form, there is also a field which is designed to update the **api-key-value attribute**. 

After clicking submit, the **api-key-value attribute** will update, but the **server-url attribute** does not. I've tried to remedy this issue using cookies, which seems to work on some browsers, but not on others.

**Comment by mrin9** [comment]
`server-url` attribute is little tricky. I may have to explain a little bit more in the API docs
but to give you a general idea , `servers` may also exist in the spec.
and if you try to change it using rapidoc's `server-url` after loading the spec it wont change it 

May be after specifying `server-url` try to  call `loadSpec(specUrl)` method. 

otherwise if it works for your use case, 
- specify the server-url on the tag `<rapi-doc server-url='xxx'> </rapi-doc>` to avoid spec reload
- if you are dealing with dynamically changing the servers, then I would recommend you to use [Server Templating ](https://swagger.io/docs/specification/api-host-and-base-path/) that way you wont get locked in with RapiDoc specific functionality and be compliant with OpenAPI spec. here is an example of how its rendered in rapidoc https://mrin9.github.io/RapiDoc/examples/server-vars.html#overview

**Comment by jonvictory** [comment]
Server templating is what I was missing. Thanks!
