### ISSUE TITLE
Highlighting missing required fields after "TRY" (Feature request)

### ISSUE THREAD

**Issue by CiaranWhyteGit** [mrin9/RapiDoc#264]
Hi , amazing project btw, quick one for you

I was thinking that it would improve the user experience if empty required fields were highlighted empty fields after a failed "TRY" click

![Screenshot 2020-07-20 at 13 41 03](https://user-images.githubusercontent.com/6874858/87938569-b0499300-ca8e-11ea-8deb-147fd0dcdd17.png)

**Comment by mrin9** [comment]
I dont think we can do that in a reasonable manner.
for starters, how do you propose that a TRY failed due to empty field ? 
There are many API implementations that returns `HTTP Status 200-OK` for missing fields, with a custom message containing error and success messages

Please feel free to reopen if you are proposing something different and you have a way to figure out and parse any generic response
