### ISSUE TITLE
Unsigned values show only ">=0" in single line description mode

### ISSUE THREAD

**Issue by ThouCheese** [mrin9/RapiDoc#280]
When I put rapi doc into single line description mode, all properties of a schema show only their minimum value, instead of their description. When the type of a property is already `unint32`, its not very useful to only show the minimum value. I think it would be more sensible to display only the `description` field instead of the `minimum` field. Is it possible to configure this?

**Comment by mrin9** [comment]
Well at rapidoc many of our decisions are backed by user-feedback.
w.r.t single line descriptions majority of our user's think constraints (min, max, enums etc) are more important than description. therefore descriptions takes a 2nd seat. 
Further, even if we show descriptions in the single line, there is no guarantee that the entire description will be shown in one line. But showing min, max etc  has a greater possibility of showing in single line and therefore will look more complete.

> When the type of a property is already unint32, its not very useful to only show the minimum value.

It is not due to the type `unint32` we show minimum constraint, we show minimum only when you put it in the spec. So if you think min constraint do not add much value where type is `unint32` then remove it from your spec and you will see description appearing in the first line if no other constraints are present

**Comment by ThouCheese** [comment]
Alright thank you for the response! I will take a look at my openapi generator and see if I can stop it from emitting the minimum.
