### ISSUE TITLE
use-path-in-nav-bar does not work

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#285]
Setting `use-path-in-nav-bar` true or false doesn't change the output of the navigation. 
https://codesandbox.io/s/magical-pond-oojwy?file=/src/App.js

**Comment by mrin9** [comment]
this is not yet released yet.
In order to use it you need to pickup the build (`rapidoc-min.js`) from https://github.com/mrin9/RapiDoc/tree/master/dist
which contains our latest build (edge release) and is not tested 
or build it yourself from the source

for reference how it works you can check it out in the example section https://mrin9.github.io/RapiDoc/examples/nav-item-as-path.html
(all our examples uses the edge release)

**Comment by mrin9** [comment]
`8.2.0` is released and the feature should be available now
