### ISSUE TITLE
Two authentication elements with same api-name and api-location being shown on rapidoc screen

### ISSUE THREAD

**Issue by JoshRozario** [mrin9/RapiDoc#313]
So im trying to provide an api-key called "Authorization" which is in the swagger spec. but instead i recieve two instances of the Authorization key with the location header on my rapidoc screen. 

Is this expected behavior or is this a bug.

Rapidoc screen:
![Screen Shot 2020-09-29 at 12 26 05 pm](https://user-images.githubusercontent.com/30451379/94505676-f5d4ca00-024e-11eb-9a7b-7ed66896aa55.png)

code:
<img width="466" alt="Screen Shot 2020-09-29 at 12 22 44 pm" src="https://user-images.githubusercontent.com/30451379/94505467-7d6e0900-024e-11eb-9564-5d1897d05d31.png">

from api:
![Screen Shot 2020-09-29 at 12 38 04 pm](https://user-images.githubusercontent.com/30451379/94506392-a1cae500-0250-11eb-9bd1-d9485b490201.png)

**Comment by mrin9** [comment]
This is an expected behavior,

OpenAPI spec only allows you to define `api-key` but you cannot provide its `value` 

This is a very common feature that our users have requested where they like to supply their own `api-key` and `value` in a declarative manner and also like to control it programmatically. Therefore RapiDoc provides a way to supply API Key and its value from outside the spec using attributes

The `api-key-name`, `key-value` and `key-location` is dynamically injected into the spec and has no connection with keys that already exist in the spec.

RapiDoc UI supports sending multiple or selective api keys during `TRY` call,  
It is common for APIs to ask for multiple API keys to resolve authorization scope

For you case I dont think it will be an issue have multiple api-keys with same name (`Authorization `) as long as you make sure that only one key is applied.

If you are concerned that it may confuse your user, then based on your needs remove the api-key either from spec or attribute
