### ISSUE TITLE
Example of (json) request body is not coloured

### ISSUE THREAD

**Issue by bligny** [mrin9/RapiDoc#318]
See attached screenshot:

- The sample json payload displayed in the **request** tab is NOT coloured although the content-type "application/json" is set
- The sample json payload displayed in the **response** tab is coloured

![image](https://user-images.githubusercontent.com/19853549/95337057-bf7ff600-08b1-11eb-8a9b-73e084401355.png)

Here is the openapi file:

```yaml
/jobs:
    post:     
      operationId: planJob
      ...          
      requestBody:       
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanJobRequest'
      responses:
        '200':                       
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanJobResponse' 
```

**Comment by mrin9** [comment]
thats because it is editable (`<textarea>`), and is sent as a plain-text (not rich text) to the server, when try button is clicked.

we wont be able to include a full fledged editor for this. (that is like asking to embed something like VS code)

We would like to contain the web component's features and size to a reasonable balance.

**Comment by bligny** [comment]
I fully understand and agree.
I'm just wondering whether the request area could be not editable by default (allowing thereby the colouring) - like the response, and add a new "Edit" button turning it into a textarea widget.
My 2 cents

**Comment by mrin9** [comment]
I have add the suggestion into our backlog queue.
