### ISSUE TITLE
Unable to link to paths that contain curly brackets

### ISSUE THREAD

**Issue by SteveNay-vz** [mrin9/RapiDoc#334]
I'm the person who created issue #80 asking for a way to link to different sections in RapiDoc output. The much-appreciated feature that was added is to use Markdown and the format `#{method}-{path}`.

That works nicely, except that I can't find a way to link to a path that contains a parameter in curly brackets, such as `/customer/{customerId}`.  Since the left-column navigation links work in "read" mode, I assume that it's possible but I haven't discovered the right link format. Can someone help me with this?

**Comment by mrin9** [comment]
I guess its an issue due to browser url-encoding.

For instance the below link when clicked will not work as expected 
https://mrin9.github.io/RapiDoc/examples/example1.html#get-/store/order/{orderId}

but if you paste/type it directly on the URL it will work. _(for that matter even updating the URL using javascript works and thats the reason it works in `read-mode`)_

Thanks for bringing it up, will provide a fix soon
