### ISSUE TITLE
Question - Can you use YAML files?

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#403]
Does this support YAML files? I'm not able to get mines to load and just seeing if JSON is the only option. Using AWS S3 bucket to host the YAML file. File passes https://github.com/p1c2u/openapi-spec-validator

**Comment by tjperry07** [comment]
Answered my own question. Converted the file to JSON and it loads.

**Comment by waldyrious** [comment]
RapiDoc definitely supports YAML files. See for example various examples of YAML files in [docs/spec](https://github.com/mrin9/RapiDoc/tree/master/docs/specs). It's possible that the particular file you were using triggered a bug in RapiDoc. Would you be able to share a simplified/anonymized version of the YAML file that reproduces the same issue? If so, I'd suggest reopening this issue so that the bug can be investigated and fixed.
