### ISSUE TITLE
UX enhancements for some buttons (search, collapse, expand, try)

### ISSUE THREAD

**Issue by reyolivo** [mrin9/RapiDoc#427]
Hi, love the new updated version. If we could add some enhancements to some of the buttons and the search bar, then it would improve things even more visually and UX wise. To start, buttons like the "Try" button, could benefit from having nicely rounded corners (pills style) as seen in the attachment.

For the focused mode, the Collapse/Expand buttons could be improved and made bigger. I think disabling or hiding the button for the state that is currently active would allow us to show bigger Expand / Collapse buttons as shown in the attachment.

We could also improve the Search bar - changing the default text to be "Quick filter" rather than "Quick Search" makes more sense given it is filtering functionality. Also, doing some UX enhancements as suggested in my attachment for this section would make things a little more intuitive.

Thanks a lot,
Rey

[rapidoc ui enhancements attachements.docx](https://github.com/mrin9/RapiDoc/files/6051936/rapidoc.ui.enhancements.attachements.docx)

**Comment by mrin9** [comment]
When providing an image, it will be better to inline them into the issue instead of providing an attachment. Having MS word installed on a system is not very common.

> buttons like the "Try" button, could benefit from having nicely rounded corners (pills style) as seen in the attachment.

It is a very personal opinion, to mitigate that we offer certain amount of customization today like `bgcolor, color and font` In future we will switch to [css ::parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) that will allow even more control to style them such as the button borders, margin, shapes, shadow etc. for now we will be going to stick with this as the decision in this regard is made by our UX team and they would have gone through a process to decide on the styles we apply today.


> For the focused mode, the Collapse/Expand buttons could be improved and made bigger. I think disabling or hiding the button for the state that is currently active would allow us to show bigger Expand / Collapse buttons as shown in the attachment.

we do not use icons in our package as we are sensitive to package size, more so, since we cannot do code splitting, the entire web-component must be in a single `.js` file for it to work. Instead of icons we use unicode symbols, that too, those which has fairly common support across OS/browser. Having said that, expand/collapse functionality is recently introduced we are still in the process of receiving user feedback. 
Personally, I think its a good suggestion to use only one button, but then we have to maintain the expand/collapse state internally. I will add this to the suggestion list of our UX suggestion


> We could also improve the Search bar - changing the default text to be "Quick filter" rather than "Quick Search" makes more sense given it is filtering functionality. Also, doing some UX enhancements as suggested in my attachment for this section would make things a little more intuitive.

we have received similar suggestion to rephrase `Quick Search` to `Filter` and `Adv. Search` to `Search`. Our UX team have collected data about it and currently interviewing some of our users w.r.t that. I will add your suggestion. But best would be if you can send me a PR making those UI changes you suggested around search functionality and I can demo them to the UX guys

**Comment by mrin9** [comment]
Support for `CSS ::parts` have been added, this will allow you to directly apply CSS to certain parts of the document.
Read about it at https://mrin9.github.io/RapiDoc/css-parts.html

**Comment by waldyrious** [comment]
> Support for `CSS ::parts` have been added

@mrin9 that's great news! I thought I'd point out that the page at https://mrin9.github.io/RapiDoc/css-parts.html seems to end abruptly in a section "CSS Variables" that has a single sentence. Was there additional content that was left out?

**Comment by mrin9** [comment]
@waldyrious , Sorry to reply late on this as i do not get notifications on closed issue, You always open a new one if you want to ask a question :)

Now to answer your query, The article was mostly about CSS parts and
CSS variables are not officially supported, we foresee some changes to their definitions, therefore we just mentioned it without giving much of a context.

**Comment by waldyrious** [comment]
Thanks for the clarification, @mrin9. I was just wondering if it was intentional, since it seemed like it could have been an overlook.

Perhaps it would make sense to either mention that "CSS variables are not officially supported, we foresee some changes to their definitions", or remove that section altogether? The way it is currently, it seems to have potential to cause confusion.
