### ISSUE TITLE
[Feature]: Hide schema toolbar

### ISSUE THREAD

**Issue by jurijzahn8019** [mrin9/RapiDoc#442]
Hi, 

i would like to be able to hide the schema toolbar especially "Singleline / Multiline Description" via property.

for examle:

```html
<rapi-doc
    ...
    allow-schema-toolbar="false"
></rapi-doc>
```

I could make a PR if you will accept the request :)

**Comment by mrin9** [comment]
We are planing some style changes around that area soon, I have added this feature request. Will work on it pretty soon, 
a PR will be fine too, but it may ultimately modified for the style.

I could foresee some changes in the way we are constructing the DOM so if you are attempting a PR, instead of hiding the entire toolbar go for allow/disallow each button on the toolbar. 
So you can rename the attribute to `allow-schema-description-multiline-toggle = true/false`

**Comment by mrin9** [comment]
done - the attribute name is `allow-schema-description-expand-toggle` check it out in the [API](https://mrin9.github.io/RapiDoc/api.html)

**Comment by jurijzahn8019** [comment]
That was fast 🙂
