### ISSUE TITLE
Bug: Cannot read property 'tags' of null

### ISSUE THREAD

**Issue by leonheess** [mrin9/RapiDoc#456]
I updated to 8.4.9 and this error is occurring every time I use `scrollTo()`

![image](https://user-images.githubusercontent.com/13834296/112973863-0d373600-9152-11eb-9dcc-b936736f44c6.png)

**Comment by mrin9** [comment]
well, there could be many reasons for that to happen and i would like to recreate this issue on my end to properly address that. Here are couple of things you can do

- Check http://localhost:8080/examples/collapsable.html and https://mrin9.github.io/RapiDoc/examples/collapsable-focused.html these two examples uses `scrollTo()` method - and you can trigger it by one of the button provided at the top. When I tested, I was not able to produce it. However these examples uses a `9.0.0-beta` version 
- Next try out the `9.0.0-beta` version to see if it fixes your case. You can pick this up from this repo at `dist/rapidoc.min.js`
- It could also be due to your spec, if none of the above works, provide me with a minimal spec that is crating this issue, the code on how you are invoking `scrollTo()` and the `<rapi-doc>`  config that you are using

**Comment by mrin9** [comment]
this was closed mistakenly due to wrong issue number in commit message ... reopening it

**Comment by leonheess** [comment]
I upgraded to 9.0.0 and I no longer get an error message but the `scrollTo()` is completely broken. Any tips on how to debug this? I put in `get-/items` but it doesn't scroll to: 
![image](https://user-images.githubusercontent.com/13834296/113833888-75a59900-978a-11eb-8dca-d96ea2531ff0.png)

**Comment by leonheess** [comment]
I made a code-sandbox to replicate the bug: https://codesandbox.io/s/vue-rapidoc-mep7u?file=/src/App.vue

**Comment by leonheess** [comment]
I could solve the issue by doing this: `rapidoc.loadSpec(spec).then(() => rapidoc.scrollTo("get-/items"))`
