### ISSUE TITLE
Rapidoc ready is too slow

### ISSUE THREAD

**Issue by Lifeclue** [mrin9/RapiDoc#461]
Hello.

I have been using Rapidoc.

Recently I tried to apply Rapidoc to a legacy product but Rapidoc shows the document too slow.

<img width="1067" alt="스크린샷 2021-04-12 오후 4 57 28" src="https://user-images.githubusercontent.com/2050435/114366936-e4358d00-9bb6-11eb-8527-79ebc1de43d7.png">

This is a screenshot that Firefox's performance result. It works slightly faster on Firefox but still very slow.

It takes too long to render the UI after loading specs.

I'm so sorry to do not attach the specs because it is internal APIs of my company.

Could you check if there are any problem?

**Comment by Lifeclue** [comment]
It is slow on 9.0.0.
I ran on 8.4.9 right now, It works perfectly.

**Comment by mrin9** [comment]
> It is slow on 9.0.0.
> I ran on 8.4.9 right now, It works perfectly.

Let me get some data on that 
- what is the size of your spec
- what `render-style` are you using ?
- whats the rendering time difference you are noticing  between 8.4.9 and 9.0.0

Refer to  `9.0.0` release notes which may give you some ideas why it could be sow , i can think of 2 reasons now
- in `9.0.0` default `render-style` is `read` which is slower than  default `render-style = view` in 8.4.9 `render-style=view` if you are depending on default setting then change it to suite your rendering needs. fastest is `focused` then `view` and then `read`
- In `9.0.0` we automatically attempt to download fonts from google CDN. There are regions where google font CDN performance is slow, if thats the case then or you dont want that to happen then set `load-fonts = 'false'` and then supply your own font from a CDN or any other server. if you dont then it will fallback on system fonts


>I got it. 8.4.9 shows a loading spinner. However 9.0.0 doesn't it.

this should have been fixed in #459 , can you give a try using the source from `dist/rapidoc-min.js` and update if thats taken care of ?

**Comment by Lifeclue** [comment]
I had confused because the loading spinner doesn't display and the default value of `render-style` had been changed to `focused`.
The loading time of Both versions seems same.

I share my test results below.

## Spec size
My spec size is 62.69KB.

```
Content-Length: 64021
```

## Loading timeline of each `render-style`

Following contents is timelines of Safari (tested on `9.0.0`)

- `render-style` is "read"

![image](https://user-images.githubusercontent.com/2050435/114578062-8a68bc00-9cb7-11eb-8ad9-fe764de53194.png)

- `render-style` is "view"

![image](https://user-images.githubusercontent.com/2050435/114578292-b84e0080-9cb7-11eb-9ee6-345beec862d2.png)

- `render-style` is "focused"

![image](https://user-images.githubusercontent.com/2050435/114578477-dddb0a00-9cb7-11eb-9f44-eb6fb3d88ce3.png)

## Conclusion

There are no problem. I'm so sorry for the confusion.

**Comment by mrin9** [comment]
cool, thanks for taking time and sharing your stats !!!
