### ISSUE TITLE
Example not shown on change in focused mode

### ISSUE THREAD

**Issue by acharlop** [mrin9/RapiDoc#470]
steps to reproduce:

1. go to: https://developer.net2phone.com/docs/webhooks#post-call_blocked
2. select the 4th example
3. select `call_answered` on the sidebar
4. `example` is selected in dropdown but not shown display is still hidden

**Comment by acharlop** [comment]
I believe I've narrowed it down to `api-resonse.js` `mimeExampleTemplate()` but not sure how to fix it

**Comment by mrin9** [comment]
If you are looking into it .... just giving you some pointers
- when you click on the navigation bar it calls `rapidoc.js > scrollTo()` method
- from here it behaves little differently based on `render-style`
- for focused mode it further make calls to
    - `api-response.js > resetSelection()` and `api-request.js > resetRequestBodySelection()` . These methods tries to reset the pervious values and show the new end-points.
    - resetting the values should update UI as it will trigger a change, may be we need to reset more values here or we may have to force an update even if there is no change using `lit-elements` method `this.requestUpdate()`
   
I am traveling, i may not be able to get to it sooner, but meanwhile if you can provide me with a small spec file where i can re-create this issue , will be helpful

w.r.t the scenario you presented above
`call_blocked` operation have 4 examples and `call_answered` has 4 examples
if you select any of top-2 examples this issue isnt occurring, the problem happens only when you select the3rd and 4th example, and I am thinking it is due to we are not resetting the example-item , therefore when it goes to `call_answered` it tries to look for 4th item in the dropdown and fails 


Thanks for digging this

**Comment by mrin9** [comment]
were you able to get your issue fixed ?
if not can you provide a minimal spec where i can recreate this issue as the initial link you have provided have changed and there isn't a quick way to research on this.
Else i would like to close this issue assuming it works fine with the latest beta
