### ISSUE TITLE
Showcasing Sequence Of API Calls

### ISSUE THREAD

**Issue by shahamit** [mrin9/RapiDoc#523]
We have a requirement to document a sequence of api calls for a specific business use case. There could be multiple such business use cases. This helps the client developer to understand the order in which the api calls need to be made to accomplish a business use case. 

Is there a standard way this requirement is tackled by anyone using rapidoc?

Thanks.

**Comment by mrin9** [comment]
There are few ways to do that
- Group related operations under a `Tag` https://spec.openapis.org/oas/v3.1.0#tag-object
- RapiDoc provides few options to arrange the operations under a tag check `sort-endpoints-by` property
  - you can sort operations by HTTP method , path or summary. 
  - For instance I will put a seq-number in front of the operation summary and then `sort-endpoints-by = summary` to get a desired order
- Finally I will sort the `tags` (_check out how to arrange tags accoring to openapi spec https://mrin9.github.io/RapiDoc/examples/arrange-by-tags.html#servers_)

Among other things 
- You can also provide lengthy descriptions using markdown on a Tag level about how to go about different flows
- Instead of just listing the endpoint, you may consider writing elaborate documentation for your APIs and arrange those topics in headings and subheadings (https://mrin9.github.io/RapiDoc/examples/markdown-headings.html)
- You may embed HTMLs and other markdown component such as https://mermaid-js.github.io/mermaid/#/ if that makes more sense  an example of using it is https://mermaid-js.github.io/mermaid/#/

Hope that helps
