### ISSUE TITLE
Mobile Navigation Bar

### ISSUE THREAD

**Issue by sk-** [mrin9/RapiDoc#536]
One thing I'm missing in the UI is a mobile menu showing the navigation bar.

**Comment by mrin9** [comment]
it is by design. 
having a navigation bar and the content on a mobile(phone) form-factor is something our UX think  isn't a good experience.

There are other ways to do things in that area, like overlays and slide-in 
but at present our primary target is for tablet and above form-factor as our data shows thats where is our 98% user base is.

I wont mind taking an PR on this if done without creating a performance issue.
