### ISSUE TITLE
Create a 3-Panel View for all themes.

### ISSUE THREAD

**Issue by SamiHK** [mrin9/RapiDoc#550]
#278 
Hi can we have a 3-Panel view like Redocly.
1st panel to have groups and list of APIs
2nd panel to have in-page links to direct to a particular API where we are able to see the request/response schemas, validators and descriptions of each API endpoint.
3rd panel to have the try-it-out feature and different code implementations.

If you need help in understanding this or technical assitance. I can be of help.
Thank you.

**Comment by mrin9** [comment]
Like to understand whats the goal here 

- Is it more usable that way,  it just looks better or more people are used to that layout ?
- list down your pain points with the rendering styles that RapiDoc supports and how those pain points can be solved through the 3 col view ?
- RapiDocs UI is one of its USP, we take our user experience very seriously and we have conducted many user feedback about our styling in the past and here are few things that I remember what our user said against 3-col-view

   - gets too crammed up in narrow devices such as tablets
   - too many duplication of information on the middle and last panel, like responses are repeated etc
   - due to duplication of information, a small spec too looks quite big and overwhelming 
   - difficult to understand due to information duplication

**Comment by mrin9** [comment]
closing due to lack of response. please feel free to open new one and provide few reasons for the change you are asking so that i can take it forward
