### ISSUE TITLE
pasting a value into a list field deletes any existing values

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [mrin9/RapiDoc#552]
If you try to paste an additional value into a list field, you replace all existing values instead of adding an additional value.

![image](https://user-images.githubusercontent.com/15961647/133287120-428b54e1-192f-41db-98b7-68800ffe360d.png)
<kbd>ctrl</kbd>+<kbd>v</kbd>  ->

![image](https://user-images.githubusercontent.com/15961647/133287211-e7fdacef-882d-48d6-887e-4cb4d8a45add.png)

**Comment by BinaryWizard904** [comment]
Just noticed this myself and it's quite annoying.  I believe it is caused by the 4fa451dc58aa0cc7071a088b56b95801f64c0ba7 commit as versions prior to this commit are unaffected.

**Comment by BinaryWizard904** [comment]
After some trial and error, I determined that the source of the problem is the afterPaste(e) function in the tag-input.js file.  The way it's written, data pasted from the clipboard overwrites existing data instead of being combined with it.

https://github.com/mrin9/RapiDoc/blob/50d8e2a28b679e31940076ce01f359f9b3dc26e1/src/components/tag-input.js#L38-L43

Compare this to how the afterKeyDown function handles entries followed by "enter".  In that function, new values are combined with the old.

https://github.com/mrin9/RapiDoc/blob/50d8e2a28b679e31940076ce01f359f9b3dc26e1/src/components/tag-input.js#L45-L56

Experimenting with possible fixes now.

**Comment by BinaryWizard904** [comment]
Binaries of 9.1.3 + the proposed fix can now be found on my fork should anyone want them for testing.
