### ISSUE TITLE
show-components doesn't work in read mode

### ISSUE THREAD

**Issue by dahu33** [mrin9/RapiDoc#558]
With RapiDoc v9.1.2 `show-components="true"` doesn't work anymore with `render-style="read"` (used to work in v9.0.x)

**Comment by mrin9** [comment]
`show-components` were never intended to be for `read-mode` in version `9.0.0` this functionality was buggy because it will  list the components on the left-nav but clicking on them will take you no where neither they were rendered in the content area.

in `9.0.x` we fixed this by removing those navigational links from the left nav

to test it out use the following `html`

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">

   <!-- rapidoc 9.0.0 -->
    <script src="https://cdn.jsdelivr.net/npm/rapidoc@9.0.0/dist/rapidoc-min.min.js"> </script> 

  </head>
  <body>
    <rapi-doc spec-url="https://petstore3.swagger.io/api/v3/openapi.json" 
      render-style="read" 
      show-components="true"
    > </rapi-doc>
 </body>
</html>
```

let me know if that answers your question

> it could be the case that `show-components` were allowed in `read` mode in older versions, however we encountered some performance issues with large specs and therefore decided to removed it from `read` mode - `v9.0.0` was a breaking change we might have used this release to removed it

**Comment by dahu33** [comment]
Gotcha makes sense now. I've switched to the `focused` mode and it solved my problem.

The `show-components` doc might need to be updated as it still mention the read mode:
> show/hide the components section both in document and menu (available only in focused render-style)
> Will show the components section along with schemas, responses, examples, requestBodies, headers, securitySchemes, links and callbacks. Also will be shown in the menu on the left (in read mode).
