### ISSUE TITLE
Text hiding with a custom header

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#579]
Trying to add a custom header. But, on clicking any title in left panel, top of the text on right panel is hidden. Any idea how to avoid this?
https://jsfiddle.net/majoshi1/ejbcpxtw/15/show

For example, on clicking API SERVER on left panel:

Expected:
![image](https://user-images.githubusercontent.com/292394/135890238-48ef09cf-1b9f-430a-9a49-5e42b6d55dcb.png)

Actual:
![image](https://user-images.githubusercontent.com/292394/135890114-fbce8401-7eea-483d-9194-2d3ed386a739.png)

**Comment by mrin9** [comment]
RapiDoc's link is behaving as expected. but the reason you are getting this is because the custom header you created is overlapping and covering the top section  of rapidoc. 

you should find a way that it do not overlap or cover the rapidoc element, either using a styling which do not break html elements positional flow which happens when you uses `css position = absolute, fixed, sticky` or try provide a top margin to rapidoc to avoid overlap

**Comment by majoshi1** [comment]
Tried using rapidoc header and it seems to work. Although, it is possible to hide logo and also use all the space in header?
[Rapidoc Header](https://jsfiddle.net/majoshi1/ejbcpxtw/42/show)
