### ISSUE TITLE
Failed to compile with 1 error  with vue-cli for Vue 2

### ISSUE THREAD

**Issue by W0nderMuffin** [mrin9/RapiDoc#658]
Hello there,

since rapidoc version 9.1.4 I'm getting the following error while building with vue-cli for vue 2:

```bash
> vue-cli-service build --target wc --name my-webcomponent --mode production


⠧  Building for production as web component...

 ERROR  Failed to compile with 1 error                                                                                                                                                                     5:24:29 PM

 error  in ./node_modules/rapidoc/dist/rapidoc-min.js

Module parse failed: Unexpected token (2:270731)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

My env:
```
    "rapidoc": "9.1.4",
    "vue": "^2.6.14",
    "vue-i18n": "^8.27.0",
    "vue-json-viewer": "^2.2.21",
    "vue-router": "^3.5.3",
    "vuex": "^3.6.2",
    "vuex-persist": "^3.1.3",
     [...]
    "@vue/cli": "^4.5.15",
    "@vue/cli-plugin-babel": "^4.5.15",
    "@vue/cli-plugin-unit-jest": "^4.5.15",
    "@vue/cli-plugin-vuex": "^4.5.15",
    "@vue/cli-service": "^4.5.15",
```

Any ideas? 9.1.3 works without compile errors 🤔

**Comment by mrin9** [comment]
I tried locally as well as publishing few experimental versions (`9.1.5` & `9.1.6` ) of rapidoc
to make it work. I am not sure if this is stemming from the vue project or any of the dependencies of RapiDoc

in the latest version `9.1.7` It works on codesandbox.io
https://codesandbox.io/s/xenodochial-leakey-me4n54?file=/package.json

but i am unable to get it working on the minimal repo you provided

the most important change between `9.1.3` and `9.1.4` which is capable of causing this issue is the upgrade of `marked` package from ver `3.x.x` to `4.x.x`

Can you try building rapidoc at your end, downgrade marked to `3.x.x` 
by reverting the following commit
https://github.com/mrin9/RapiDoc/commit/7b7a23025d1d861314ac8b5b9abafec2b05517ef

and see if it works with your project

**Comment by mrin9** [comment]
finally I was able to figure out the dependency that was responsible for this issue 
please use release `v9.1.8` and confirm if it is working for you

**Comment by W0nderMuffin** [comment]
thanks for fixing it 👍
it seems to work with `9.1.8` 🎉
