### ISSUE TITLE
About the collapse-all of nav-bar-tag-and-paths

### ISSUE THREAD

**Issue by complete-fangzr** [mrin9/RapiDoc#676]
How does the interface menu collapse by default

**Comment by mrin9** [comment]
in `read` mode we wont be allowing to collapse the menu as the scrolling the main section automatically highlights the selected menu on nav-bar section. Adding collapse/expand will create too much of screen activity during a scroll.

for `focused` mode let me see if its possible to add this option

**Comment by rakshassa** [comment]
Can we collapse/expand individual tags in the nav-bar section?
Can we "collapse/expand all" tags in the nav-bar section?

**Comment by mrin9** [comment]
After a discussion, we decided not to provide this option at the RapiDoc level as it can contradict our vendor extension `x-tag-expanded`

This vendor extension can be selectively applied to each tag that should be expanded/collapsed rather than colapsing the whole menu.
 
Check out this example for more details 
https://mrin9.github.io/RapiDoc/examples/collapsable.html

**Comment by WilliamStam** [comment]
so to close all the tags you would need to add `x-tag-expanded: false` to each? ouch.,..

when using fastapi you dont get such luxuries :( so ive gone through and added the name: ... stuff to a custom openapi class in fastapi. the json looks like this:

```
"/instances/{instance_id}/accounts": {
            "get": {
                "tags": [
                    {
                        "name": "instances | accounts",
                        "x-tag-expanded": "false"
                    }
                ],
```
but with this i get a 
![image](https://github.com/rapi-doc/RapiDoc/assets/182800/a63632d9-c969-41a0-b66d-e85262e67ece)
