### ISSUE TITLE
GET/POST on left panel & Styling

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#682]
Is it possible to show GET/POST on left panel?
Below is a mockup from [this](https://mrin9.github.io/RapiDoc/examples/themes.html) example.

![image](https://user-images.githubusercontent.com/292394/157105769-15708a4d-3cbe-4be7-9c1f-75db6d392237.png)

This is based on following image on [API](https://mrin9.github.io/RapiDoc/api.html) page. 
Also, where to find the this example?

![image](https://user-images.githubusercontent.com/292394/157104187-6d74d3a8-274a-4e0f-aecb-76677dbddd66.png)

**Comment by mrin9** [comment]
> Is it possible to show GET/POST on left panel?

- It is little tricky for us to do that.
   - one, because we allow customizing background color of nav-bar, so if someone choose a blue background for the nav-bar, `POST` will get mixed up with that as its background is also blue. Also it can lead to a poor contrast ratio. Anyways, let me take it our UX team and lets see what they have to say
   - two, `GET`, `POST` makes more sense when they are preceded before a path not before summary / description. If you like to show method and path on nav bar  try using `use-path-in-nav-bar = 'true'`


> Also, where to find the this example?

all our examples and test cases are listed  at https://mrin9.github.io/RapiDoc/list.html
the example you are looking for is may be https://mrin9.github.io/RapiDoc/examples/example1.html

**Comment by majoshi1** [comment]
Thanks fir your response. Is it possible to show left panel, when render-style=view?

**Comment by mrin9** [comment]
> Thanks for your quick response. Is it possible to show left panel, when render-style=view?

 
No, but you can create your own. example  https://www.northbricks.io/apis/

**Comment by majoshi1** [comment]
>   * one, because we allow customizing background color of nav-bar, so if someone choose a blue background for the nav-bar, `POST` will get mixed up with that as its background is also blue. Also it can lead to a poor contrast ratio. Anyways, let me take it our UX team and lets see what they have to say

Thanks.

>   * two, `GET`, `POST` makes more sense when they are preceded before a path not before summary / description. If you like to show method and path on nav bar  try using `use-path-in-nav-bar = 'true'`

Agreed, but having icons may be more user-friendly. Otherwise, is it possible to add a new flag  `use-operation-in-nav-bar = 'true'` to show operation and summary?

> all our examples and test cases are listed at https://mrin9.github.io/RapiDoc/list.html the example you are looking for is may be https://mrin9.github.io/RapiDoc/examples/example1.html

Thanks, will explore this along with example https://www.northbricks.io/apis/

**Comment by mrin9** [comment]
[Test case](https://mrin9.github.io/RapiDoc/examples/nav-item-with-method.html)

**Comment by Foorack** [comment]
# Notice
For anyone else stumbling upon this PR, the setting to enable this feature is not `use-operation-in-nav-bar = "true"` as mentioned in above comments, but rather `show-method-in-nav-bar = "as-colored-block"`.
