### ISSUE TITLE
Required parameters not checked

### ISSUE THREAD

**Issue by baguse** [mrin9/RapiDoc#701]
![image](https://user-images.githubusercontent.com/36828138/159633617-c8380fa4-a304-4c13-be0d-37d977d16d84.png)

Request can be send without inputing required parameters

**Comment by mrin9** [comment]
Yes, thats on purpose.
Its not a goal of RapiDoc to  become a perfect client for the API. 

Instead it allows you to test how your API behaves when you provide incorrect data.

**Comment by mhdsysy** [comment]
@mrin9 First of all thanks a lot for putting such an effort into RapiDoc, this is def a game changer.
I don't quite agree actually with what you said, the UI is not for testing the behaviour of the API, also there is no need to show the red dot of required path parameter if the request will be fired anyway.

Also in my case i am using JAX-RS, and JAX-RS breaks RFC 1808 in that it matches the paths @Path("/bla") and @Path("/bla/") to the same resource. This is a problem, since now there is no way to distinguish between @Path("/bla/{parameter}") and @Path("/bla), where the first one is expected to give a certain entity of type "bla" if found, and the latter is expected to give all entities of type "bla" if any.
And the only way to fix this is to check in every resource class whether the uri that should end with a path parameter does indeed end with a path parameter or just a slash.

**Comment by mhdsysy** [comment]
If anyone is wondering, is is a dirty hack i did to avoid writing code in 84 classes.

`<script>
    window.addEventListener('DOMContentLoaded', (event) => {
        /*
          Ensure that the DOM is loaded, then add the event listener.
          here we are listening to 'before-try' event which fires when the user clicks
          on TRY.
        */
        const rapiDocContainer = document.getElementById('rapid-doc-container');

        rapiDocContainer.addEventListener('before-try', (e) => {
            const mainBody = rapiDocContainer.shadowRoot.querySelector("div#the-main-body.body");
            const mTable = mainBody.getElementsByClassName("expanded-req-resp-container")[0]
                    .getElementsByTagName("api-request")[0].shadowRoot.querySelector(".m-table");
            const inputFields = mTable.getElementsByTagName('input');
            for (var i = inputFields.length - 1; i >= 0; i--) {
                const inputField = inputFields[i];
                if (!inputField.value.trim().length) {
                    e.detail.controller.abort();
                }
            }
        });
    });
</script>`

**Comment by mhdsysy** [comment]
If anyone is wondering, is is a dirty hack i did to avoid writing code in 84 classes.

```jsx
<script>
window.addEventListener('DOMContentLoaded', (event) => {
        const rapiDocContainer =document.getElementById('rapid-doc-container');

        rapiDocContainer.addEventListener('before-try', (e) => {
            const mainBody = rapiDocContainer.shadowRoot.querySelector("div#the-main-body.body");
            const mTable = mainBody.getElementsByClassName("expanded-req-resp-container")[0]
                    .getElementsByTagName("api-request")[0].shadowRoot.querySelector(".m-table");
            const inputFields = mTable.getElementsByTagName('input');
            for (var i = inputFields.length - 1; i >= 0; i--) {
                const inputField = inputFields[i];
                if (!inputField.value.trim().length) {
                    e.detail.controller.abort();
                }
            }
        });
    });
</script>
```

**Comment by mrin9** [comment]
> the UI is not for testing the behaviour of the API, also there is no need to show the red dot of required path parameter if the request will be fired anyway.

RapiDoc primarily is a documentation tool, therefore it is very much important to document whats required and whats not irrespective of weather you can make an API call or not,  same goes with other constraints such as min-length, pattern etc. Just because we cannot execute the API wont stop RapiDoc to document various constraints associated with parameters

further we have many customers who would disable the TRY functionality altogether yet they would like to show whats required and whats not and every other constraint

> the UI is not for testing the behaviour of the API

Well primarily the UI is for documentation, however the next most important objective of RapiDoc to allow for a quick testing of the API

> If anyone is wondering, here is a dirty hack i did to avoid writing code in 84 classes.

I would say thats not a dirty hack, instead is THE BEST way to handle this situation, and one of the reason for us to provide those hooks. Thanks for sharing the code I am sure this will help someone in your situation
