### ISSUE TITLE
Feature Show API Method names in the navigation bar is not working on the latest release 9.2.0

### ISSUE THREAD

**Issue by vpikus** [mrin9/RapiDoc#717]
Hi.

``show-method-in-nav-bar`` property is not working at all on the latest release version 9.2.0 https://unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js

It only works on 9.2.0-beta version https://mrin9.github.io/RapiDoc/rapidoc-min.js

Does anybody know why this feature is documented in the latest documentation but it's not present in the latest release? It's quite confusing...

**Comment by mrin9** [comment]
our beta release naming is little wacky, so `9.2.0-beta` is actually `9.3.0-beta` and thats because some of our internal process where we try to strip out closed source code from the open-source.

The documentation is always on latest unreleased version, this will continue to be the case for some time till we figure out a proper way to tag attributes availability with releases
