### ISSUE TITLE
Is not showing x-code-samples

### ISSUE THREAD

**Issue by axpira** [mrin9/RapiDoc#76]
In the UI is not showing the samples in x-code-samples

**Comment by mrin9** [comment]
`x-code-samples` is not a standard from OpenAPI spec. Its a user extension. At present RapiDoc do not support any user extension

**Comment by MortenHofft** [comment]
I see that has since changed
https://mrin9.github.io/RapiDoc/api.html

x-code-sample x-codeSample | Use this vendor-extension to provide code samples in various languages | [Usage example](https://mrin9.github.io/RapiDoc/examples/code-samples.html#get-/no-badges-path)
--|--|--



but the example link looks like it is something else?
https://mrin9.github.io/RapiDoc/examples/code-samples.html#get-/no-badges-path

**Comment by MortenHofft** [comment]
https://github.com/mrin9/RapiDoc/blob/master/docs/examples/code-samples.html#L18
should presumably just be updated to `<rapi-doc spec-url="../specs/code-samples.yaml"`
